### ISSUE TITLE
gabbacolors

### ISSUE THREAD

**Issue by bcube2** [cubing/AnimCubeJS#11]
I am on mobile-phone right now so can't really look into the source code, but on http://irbsystems.com/test2/rc/animcube_customization2.html there are black and white arrow-stickers on the first two supercubes (I think white ones on the left-hand side cube should be black ones).

On a side note: Michael, viewing your site is kind of dangerous for me. Either I can't sleep at night at all because of excitement of your development or I just can't pick between the variants you present because one is more beautiful than the other...

As always, thank you for your effort and perfect work.

Edit: ok, the supercube on the left hand side would probably have black arrow-stickers if in colorscheme parameter would be K instead of W...

Two observations: for some reason edit=1 doesn't work on the left-hand side supercube. On 4x4x4 supercube it works fine however (for both gabbacolors=0 and gabbacolors=1), as well as on a classical 3x3x3 cube with gabbacolors=1.

For both 3x3x3 and 4x4x4 gabbacolors=1 parameter it is necessary to refresh the page after uploading the new JS files (which is strange for me). But then the change appears no problem (so it is not a bug really).

**Comment by bcube2** [comment]
I have learnt how to view a source code on a mobile phone and as a result, I got an answer to previous 

"for some reason edit=1 doesn't work on the left-hand side supercube."

It is because of a sign ";" instead of required "&", so the simulator probably ignores whatever value in edit parameter is given and set it to a default state, which is 0.

Seems like this issue can be closed :-)

**Comment by mfeather1** [comment]
Glad you like it, I think I've reached the end of what I can do with AnimCube so you should be able to sleep now... :)

I replaced the W with K in the animcube_customization2.html (thanks for pointing that out), I had made  W into K automatically with the gabbacolors option (so I had switched them all back to W in the html) but that frame was showing Supercube without using the option so that's why it needed the K.  The edit got fixed when I made some other changes (put in green gabba background).

Yes, refresh is needed for new JS files because of browser caching, depending on platform I have different ways of doing it (Ctrl-R, Ctrl-Shift-R or view source on the call to animcube in the html and refresh that), use whatever works best for you.

**Comment by bcube2** [comment]
"Yes, refresh is needed"

Actually, I blame google for that. I tried to satisfy its foolish bot by adding

<IfModule mod_expires.c>
ExpiresActive On
ExpiresDefault A605000
ExpiresByType text/javascript A605000
ExpiresByType application/javascript A605000
ExpiresByType text/css A605000
ExpiresByType image/gif A605000
ExpiresByType image/png A605000
ExpiresByType image/jpg A605000
ExpiresByType image/x-icon A605000
ExpiresByType text/html A60
</IfModule>

<IfModule mod_deflate.c>
<FilesMatch "\.(js|css)$">
SetOutputFilter DEFLATE
</FilesMatch>
</IfModule>

into .htaccess. I don´t know, maybe it is connected somehow (instead of 1 refresh I must do 2 of them since this change of .htaccess). But that´s not important. Important thing is that your simulator works perfectly.

P.S. it removed angle brackets for reason unknown, but I think it is still clear to you what I originally wrote before its removing....

**Comment by mfeather1** [comment]
It's my understanding that the caching of JS is done by the browser so it's not an issue with Google.  I also don't think it's a bad thing because normally you want the cached copy since it loads faster and for the few times you need an updated copy it's not that hard to coerce a reload.
