### ISSUE TITLE
Centering InfoText, Font size of InfoText and Continuation of InfoText from the bottom line

### ISSUE THREAD

**Issue by BakiTANRISEVEN** [cubing/AnimCubeJS#43]
1. Hello, I want the info text to be centered within the canvas. How is this possible?

2. In some cubes, the info texts do not fit within the width of the canvas. What needs to be done to ensure that the parts of the info text that do not fit within the canvas, namely the invisible parts, continue from the bottom line?

3. Is it possible to adjust the info text font size for responsive design? Cube sizes change in Responsive, but the info text font size does not change.    

![1](https://github.com/user-attachments/assets/2bbb4e86-5d5c-4443-bb6b-59b6194d24e4)
Centering InfoText

![2](https://github.com/user-attachments/assets/e8dc3f8e-2554-49e3-aa53-ff38ab731684)
![3](https://github.com/user-attachments/assets/6a25a5da-492d-4936-9428-5985d42cd45e)
![4](https://github.com/user-attachments/assets/1cd268ac-d7b3-4cc9-b35d-d98ce9f4f5ed)
Font size of InfoText

**Comment by mfeather1** [comment]
```
1. Hello, I want the info text to be centered within the canvas.
   How is this possible?

   It can be centered as long as it fits in the width of the cube area
   otherwise it will be cut off.

   In the section where it writes the info text (near end of paint function):

   change:
   drawString(graphics, infoText[curInfoText], outlined ? dpr : 0, adjTextHeight());

   to:
   drawString(graphics, infoText[curInfoText], (width-w)/2 + dpr, adjTextHeight());

2. In some cubes, the info texts do not fit within the width of the canvas.
   What needs to be done to ensure that the parts of the info text that do
   not fit within the canvas, namely the invisible parts, continue from the
   bottom line?

   That would require coding a mini word processor to split the text on word
   boundaries to fit the varying character widths into multiple lines inside
   a varying cube area size (changes based on zoom level), this is beyond
   the scope of what AnimCube is designed for.
   For this reason, long text descriptions for move sequences are probably
   best shown outside the cube area (in the body of web page) where all
   of the formatting capabilities of html are available.

3. Is it possible to adjust the info text font size for responsive design?
   Cube sizes change in Responsive, but the info text font size does not
   change.

   Text size adjusts to zooming (ctrl + scroll) which changes both width &
   height proportionally, changing only the width does not adjust text size.
   If resizing width only, a way to prevent text cut off is to use min-width
   on the cube div.
```

**Comment by mfeather1** [comment]
Regarding info text I would add that it is probably best used for adding markers to be referenced by text descriptions on the web page.  So for example, if a long sequence has three parts then at the start of each one there could be an info text indicating that.

**Comment by bcube2** [comment]
Hi BakiTANRISEVEN,

although not what you were originally asking for, notice that you can also change the default size of the text comments (info text) by using the [textsize parameter](https://animcubejs.cubing.net/animcubejs.html#textsize).

If needed, both the move counter and textual representation of a move sequence to be played can be disabled/hidden by the counter and movetext parameter settings - which seems to be not your use case though.

**Comment by BakiTANRISEVEN** [comment]
> Merhaba BakiTANRISEVEN,
> 
> Her ne kadar başlangıçta istediğiniz bu olmasa da, [textsize parametresini](https://animcubejs.cubing.net/animcubejs.html#textsize) kullanarak metin yorumlarının (bilgi metni) varsayılan boyutunu da değiştirebileceğinizi unutmayın .
> 
> Gerekirse, hem hamle sayacı hem de oynanacak hamle dizisinin metinsel gösterimi, sayaç ve hamle metni parametre ayarlarıyla devre dışı bırakılabilir/gizlenebilir - ancak bu sizin kullanım durumunuz gibi görünmüyor.

Yes, not exactly, but the text size parameter does the job partially.

**Comment by BakiTANRISEVEN** [comment]
> Hi BakiTANRISEVEN,
> 
> although not what you were originally asking for, notice that you can also change the default size of the text comments (info text) by using the [textsize parameter](https://animcubejs.cubing.net/animcubejs.html#textsize).
> 
> If needed, both the move counter and textual representation of a move sequence to be played can be disabled/hidden by the counter and movetext parameter settings - which seems to be not your use case though.

Yes, not exactly, but the text size parameter does the job partially.

**Comment by mfeather1** [comment]
I spoke too soon, it's not as bad as all that.  I found a wraptext function from https://www.html5canvastutorials.com/tutorials/html5-canvas-wrap-text-tutorial and implemented it in AnimCube3.js.  The included web page shows tests of fonttype 0 and 1 with textsize 8, 12, 16 & 20.  Seems to work ok so we can give it a try and see how it goes.
[wraptext.zip](https://github.com/user-attachments/files/16920225/wraptext.zip)

**Comment by BakiTANRISEVEN** [comment]
> I spoke too soon, it's not as bad as all that. I found a wraptext function from https://www.html5canvastutorials.com/tutorials/html5-canvas-wrap-text-tutorial and implemented it in AnimCube3.js. The included web page shows tests of fonttype 0 and 1 with textsize 8, 12, 16 & 20. Seems to work ok so we can give it a try and see how it goes. [wraptext.zip](https://github.com/user-attachments/files/16920225/wraptext.zip)

This is great Mr. Michael Feather. This is exactly what I wanted. I have comments at the beginning and middle of the algorithm. So it would be insufficient to write these comment lines outside of AnimCube. Thank you very much. I wish you healthy days. Good work.

**Comment by mfeather1** [comment]
Glad to hear it.

I need to make a correction to what I said earlier about text size adjusting.  It adjusts based on the devicePixelRatio which changes with zooming but not with responsive design because while changing the size of the window changes the cube size it does not change the devicePixelRatio hence the text size remains the same. It appears that the addition of wrap text eliminates the issue of text getting truncated when cube size is reduced with responsive design because it gets wrapped instead.  Here is another test page for responsive design, you probably tested it already but I'm putting it here for future reference.

[responsive.zip](https://github.com/user-attachments/files/16923600/responsive.zip)

**Comment by bcube2** [comment]
Support for multiple lines of text comment has been implemented into the AnimCubeJS program. Closing.

**Comment by kupietools** [comment]
Sorry, can we reopen this? Multiple lines of text does not work for me, text just gets cut off at the right edge instead of wrapping. This is also not mentioned in the documentation's enhancement section. All I see are mentions here and on https://www.speedsolving.com/threads/animcubejs-an-animated-web-cube.84762/page-2 that this works, with no further documentation or explanation how to actually get it to happen. I do see it working on https://animcubejs.cubing.net/sources/codes/enhancement/parameters/cube3.html?move={This%20text%20comment%20goes%20on%20and%20on%20without%20saying%20pretty%20much%20of%20anything.%20Change%20the%20window%20width%20to%20see%20how%20the%20text%20gets%20wrapped.}&buttonbar=2&counter=0&textsize=16&buttonheight=20 but again there is no explanation, and the js file is minified so I can't easily see what's happening there. Can we get some explanation or documention how to get this feature working? Thanks. 

I am using the latest version from this repo, downloaded just a few days ago. 

<img width="333" alt="image" src="https://github.com/user-attachments/assets/f76a9e0e-776a-496d-9c09-7f539299a0cb">


EDIT: Belay that, I found the functions in responsive.zip above and copied them into my AnimCube3.js file. Although if there's a better way to do it than that, please let me know.

**Comment by bcube2** [comment]
> I am using the latest version from this repo, downloaded just a few days ago.

Please check and confirm again you really do as the multiple lines of text feature had been added "just a few days ago".

The working demo you saw [here](https://animcubejs.cubing.net/sources/codes/enhancement/parameters/cube3.html?move={This%20text%20comment%20goes%20on%20and%20on%20without%20saying%20pretty%20much%20of%20anything.%20Change%20the%20window%20width%20to%20see%20how%20the%20text%20gets%20wrapped.}&buttonbar=2&counter=0&textsize=16&buttonheight=20) is using the latest version of the AnimCube3.js file which is a minified AnimCube3-unminified.js file.

**Comment by kupietools** [comment]
Thanks—yeah, the commit history says AnimCube3.js and AnimCube3-unminified.js were committed on Oct. 5. I first downloaded on Oct. 9. Strange. 

As I said, I merged the code myself, so no practical issue on my end. Still, weird.

**Comment by bcube2** [comment]
> As I said, I merged the code myself, so no practical issue on my end. Still, weird.

Note that at the moment, the JS files from the Enhancement section are not necessarily up to date with the minified or unminified AnimCube3.js file. It seems you have been originally using a JS file from the Enhancement section (e.g. for the Markers mod) instead of AnimCube3-unminified.js file.
